### PR TITLE
Some necessary bugfixes to make it work with Ocotopus SatIP boxes

### PR DESCRIPTION
**Pull request by leecher1337**
- Fixed some parsing bugs that prevented rtsp-proxy to work with Octopus octoserv SAT-IP server.
- Fixed an infinite loop on closing open connections
- Refreshing last active timestamp of server and client connection is necessary during streaming so that SAT-IP stream doesn't stall.

### CODE REVIEW

**Comment by alexte** [comment]
I understood the problem with header translation and parsing now. It should be fixed now.

The other problem with stalled UDP sockets, I still don't see.
At the moment UDP proxy connections are not removed at all (only with TEARDOWN).
Perhaps the stalling occured before the timeout check loop was fixed.

VLC is keeping the TCP connection open, Kathrein isn't. Therefor this timeout loop bug was triggered by VLC but not with Kathrein.

Thanx! I close this pull request for now. If this last problem still occurs for you reopen an issue or pull request.

**Comment by leecher1337** [comment]
Maybe the periodic OPTION request is just on normal SAT>IP operation, but not on using the RTSP-streams directly like I did? Anyhow, I think refreshing the connections cannot hurt as it would be closed anyway if the other connections that keep it alive time out (as there is no more refresh then)

**Comment by alexte** [comment]
For other clients the TCP connection is already closed, and your code would set lastact for a totally different session.

Is the VLC RTSP still stopping after the changes we made ?

**Comment by leecher1337** [comment]
Yes, connection still stalls without my patch. 
I assumed according to start_udp_proxy that TCP control connection is always followed by the f_udprcv pair from start_udp_proxy, therefore my quick & dirty fix works, but of course you can try to do a cleaner patch that ensures that the TCP connection stays open as long as there is UDP traffic on the ports belonging to the TCP control connection and the associated TCP connection has not been closed by the client.

**Comment by alexte** [comment]
That's interesting. I tested with VLC and it worked for hours even without the tcp connection. 
What could be the difference ? I tested VLC on debian 7.

A correct fix could be, if we connect the udp and tcp sockets in the session object, and do the session timeout instead of a socket timeout. What do you think ? Your current fix fails for clients that close the tcp socket immediately, and do OPTION polling as described in the SAT>IP spec.

**Comment by leecher1337** [comment]
Maybe it's the octopus that doesn't like the tcp connection to be closed which would make sense as this is a good way to determine if the client is still there. Do you want to make these changes for a correct fix or should I try it?

**Comment by alexte** [comment]
That makes sense. Octopus stops streaming and InvertoMultibox continues streaming.

My quick fix is that I disabled the TCP idle timeout at all. The current idle timer is broken, and has to be fixed. That means the current code has a memory (socket) leak, if a client and server disappears without closing a socket.

**Pull request closed without merging**
