### PR TITLE
Reconnect to server when it disconnects

### PR DESCRIPTION
**Pull request by lars18th**
When the target SAT>IP server closes the connection it's not required to close the connection with the client. Then this patch implements the reconnection to the server only.

### CODE REVIEW

**Comment by alexte** [comment]
Thank you for your patch.
I understand you patch, but I don't know if this is the right thing to do.

The information that the server disconnects might be useful to the client.
For example perhaps the server is restarting, and the client uses this information and restarts the UDP streaming part in this case, after reconnecting.

If the client doesn't know that the server dropped the connection, it might miss this information.

**Comment by lars18th** [comment]
Hi @alexte ,

The SAT>IP protocol, regarding the CONTROL layer, is a subset of the RTSP protocol (with some extensions). And inside the RTSP protocol is not common that the _server_ closes the session. Actually is expected that the _client_ closes the TCP session. So this patch is to make this disconnection transparent to regular clients.

If you don't want this behaviour (transparent reconnections) as default, then a simple flag can be used to enable/disable it. What you think?

**Comment by alexte** [comment]
As option it would not hurt of course.

In what cases does this transparent reconnect help ?
What's the issue you want to fix with this patch ?

I think the server drops the connection only when the server stops or fails, and the client should always know that.

**Comment by lars18th** [comment]
Hi @alexte ,

> As option it would not hurt of course.

OK.

> In what cases does this transparent reconnect help ?
> What's the issue you want to fix with this patch ?
> 
> I think the server drops the connection only when the server stops or fails, and the client should always know that.

I detected this problem with some SAT>IP servers based on STBs. In particular with XORO STBs, but I feel others servers can have similar behaviour. These devices close the RTSP connection after 1-2 seconds of no more requests. So, the client requires to re-connect to the server. This can be done after the socket is closed and before a new request. This behaviour doesn't hurt the common SAT>IP protocol, but it's inefficient.

**Comment by alexte** [comment]
I see.

These boxes are new to me.

Would you help and change your code to make it optional, and move around the code that "reconnect" does only "reconnect", and keep the dropconnection out of this function ? 
Like this:
int reconnect(i)
{
    ... 
    close()
    ..fd=connect_server();
    return (...fd>=0);
}

if(len<=0)
{
if(type==f_server && try_reconnect && reconnect()) continue;
dropconnection();
}
I think that's a bit cleaner.

**Comment by lars18th** [comment]
Hi @alexte ,

I'll try to improve this PR. So, I will use your suggestion, and perhaps I'll add something related to #4. The main problem is that we need to reconnect only for a period, and then inform to the client if we can't reconnect. Futhermore, it's necessary to not block the client connection while reconnecting to the server. I observed this in several cases using this current patch. So there is room for improvement

Regards.

**Comment by lars18th** [comment]
Hi @alexte ,

All your recomendations are included in the new PR #19, so I close this.

**Pull request closed without merging**
