### PR TITLE
extendend dump commands over stdout

### PR DESCRIPTION
**Pull request by lars18th**
Introduced a new optional command to debug the SAT>IP protocol to the stdout.

This works similar to DEBUG, but it's different. First, it prints over the STDOUT and not over the STDERR (that uses the DEBUG). Messages are lines printing the SAT>IP command and optionally the _received_ and the _translated_ arguments of the command. All is tabulated for easy use.

Example with `-e` and `2>/dev/null` (to silent debug):
```
$$ PROTO $$ | OPTIONS
$$ PROTO $$ | SETUP
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | TEARDOWN
$$ PROTO $$ | OPTIONS
$$ PROTO $$ | SETUP
$$ PROTO $$ | PLAY
$$ PROTO $$ | PLAY
$$ PROTO $$ | OPTIONS
$$ PROTO $$ | PLAY
$$ PROTO $$ | TEARDOWN
```

Example with `-e -e` and `2>/dev/null`:
```
$$ PROTO $$ | OPTIONS | rtsp://192.168.1.37:554/ | rtsp://192.168.1.39:554/
$$ PROTO $$ | SETUP | rtsp://192.168.1.37:554/?src=1&freq=10744&msys=dvbs&plts=off&fec=56&pol=h&ro=0.35&sr=22000&mtype=qpsk | rtsp://192.168.1.39:554/?src=1&freq=10744&msys=dvbs&plts=off&fec=56&pol=h&ro=0.35&sr=22000&mtype=qpsk
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?addpids=0,17,16 | rtsp://192.168.1.39:554/stream=1?addpids=0,17,16
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?delpids=0,17,16 | rtsp://192.168.1.39:554/stream=1?delpids=0,17,16
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?addpids=0,100,200,400,500,600,17,16 | rtsp://192.168.1.39:554/stream=1?addpids=0,100,200,400,500,600,17,16
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?delpids=0,100,200,400,500,600,17,16 | rtsp://192.168.1.39:554/stream=1?delpids=0,100,200,400,500,600,17,16
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?addpids=17,0 | rtsp://192.168.1.39:554/stream=1?addpids=17,0
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?delpids=17,0 | rtsp://192.168.1.39:554/stream=1?delpids=17,0
$$ PROTO $$ | TEARDOWN | rtsp://192.168.1.37:554/stream=1 | rtsp://192.168.1.39:554/stream=1
$$ PROTO $$ | OPTIONS | rtsp://192.168.1.37:554/ | rtsp://192.168.1.39:554/
$$ PROTO $$ | SETUP | rtsp://192.168.1.37:554/?src=1&freq=10744&msys=dvbs&plts=off&fec=56&pol=h&ro=0.35&sr=22000&mtype=qpsk | rtsp://192.168.1.39:554/?src=1&freq=10744&msys=dvbs&plts=off&fec=56&pol=h&ro=0.35&sr=22000&mtype=qpsk
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?addpids=201,202,0,200 | rtsp://192.168.1.39:554/stream=1?addpids=201,202,0,200
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?addpids=204 | rtsp://192.168.1.39:554/stream=1?addpids=204
$$ PROTO $$ | OPTIONS | rtsp://192.168.1.37:554/ | rtsp://192.168.1.39:554/
$$ PROTO $$ | PLAY | rtsp://192.168.1.37:554/stream=1?delpids=201,202,0,200,204 | rtsp://192.168.1.39:554/stream=1?delpids=201,202,0,200,204
$$ PROTO $$ | TEARDOWN | rtsp://192.168.1.37:554/stream=1 | rtsp://192.168.1.39:554/stream=1
```

You can use the `awk` tool or anything else to parse the results searching for the separator char `|`.
Futhermore, you can save the output to a file or use it in realtime with a pipe (`rtsp-proxy -e ... | awk -F"|" '{ print $2 }' -`).

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @alexte ,

That's very useful for realtime debug of the SAT>IP protocol. For example, you can execute it with
- `rtsp-proxy -d -e | socat - udp-sendto:127.0.0.1:12345`

and then can show the in the console the debug commands, but in a remote console with
- `socat - udp4-listen:12345,reuseaddr,fork,bind=127.0.0.1`

You can see the commands. Futhermore, with these commands you can trigger some actions or route them to a broker (MQTT or ZeroMQ, for example).

I hope you want to merge it!
Regards.

**Comment by alexte** [comment]
nice patch, but should be simpler.

Why "$$ PROTO $$" in every line ?
And "remote_dump_send" is actually a "printf", isn't it ?

**Comment by lars18th** [comment]
> nice patch, but should be simpler.

Thank you!

> Why "$$ PROTO $$" in every line ?

That's to _identify_ the line. It can be "$$ SAT>IP $$" or whatever you suggest. The idea is this: When you print _both_ (stdout & stderr) in the screen, with this it's very easy to identify the source. Futhermore, if you _route_ these messages to some broker then you can distinguish the source. Anyway if you have a more user friendly suggestion, then please comment it.

> And "remote_dump_send" is actually a "printf", isn't it ?

It's more or less this... but I prefer to encapsulate it inside a funtion for improve the read of the code and to make more easy to incorporate changes. For example, if you want to send the message over UDP datagrams or connected with a broker.

So, please share your comments.

**Comment by lars18th** [comment]
Hi @alexte ,

You tested it?

**Pull request merged**
